#
# Copyright (c) 2022-2023 SMALLPROGRAM <https://github.com/smallprogram>
# Description: Auto compile
#
name: "Auto compile with openwrt sdk for luci-theme-peditx"
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  push:
    branches:
      - 'main'
    paths:
      - 'luci-theme-peditx/Makefile'
env:
  TZ: Asia/Tehran
  theme_repo: peditx/luci-theme-peditx

jobs:
  build_theme:
    name: Build luci-theme-peditx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib \
                                  g++-multilib gettext git libncurses-dev libssl-dev \
                                  python3-distutils python3-setuptools rsync swig \
                                  unzip zlib1g-dev file wget

      - name: Cache OpenWrt SDK
        uses: actions/cache@v4
        with:
          path: sdk
          key: openwrt-sdk-x86_64

      - name: Download and prepare OpenWrt SDK
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          mkdir sdk && tar -xJf openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz -C sdk --strip-components=1

      - name: Configure OpenWrt feeds
        run: |
          cd sdk
          echo "src-git packages https://github.com/openwrt/packages.git" > feeds.conf
          echo "src-git luci https://github.com/openwrt/luci.git" >> feeds.conf
          echo "src-git theme_repo https://github.com/${{ env.theme_repo }}.git;main" >> feeds.conf
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build luci-theme-peditx
        run: |
          cd sdk
          echo "CONFIG_PACKAGE_luci-theme-peditx=m" > .config
          make defconfig
          make package/luci-theme-peditx/{clean,compile} -j$(nproc)

      - name: Archive the built packages
        run: |
          mkdir -p output
          cp sdk/bin/packages/x86_64/theme_repo/*.ipk output/

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
